### ISSUE TITLE
Not rendering after migrate to v3.0.5 of d3-graphviz

### ISSUE THREAD

**Issue by rodneicouto** [magjac/d3-graphviz-angular#1]
After migrate to last d3-graphviz version, i get this error: 

`core.js:15724 ERROR Error: Uncaught (in promise): RuntimeError: abort(RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
RuntimeError: abort(RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at abort (index.es6.js:150)
    at index.es6.js:150
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:17299)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:390)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at resolvePromise (zone.js:831)
    at zone.js:896
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)`

If i rollback to version 2.6.0 everything works fine.

**Comment by lohithreddyk** [comment]
I had the same issue when importing it to angular. Is there any work around to update it 3.1.0

**Comment by magjac** [comment]
Sorry for the long response time. This completely slipped my mind :flushed: 

It's now fixed by creating a symbolic link to the WASM file from a folder below the assets folder and specifying that folder with [wasmFolder()](https://github.com/hpcc-systems/hpcc-js-wasm#wasmFolder).

**Comment by lohithreddyk** [comment]
When  i run production code i am getting a error of invalid asm.js  global variable not defined . Is there a work around for using web workers in angular?
